[theme]
base="light" #"dark"
primaryColor="#4653ff"  # "#253347" #"#5252e0"
backgroundColor="#f0f4fc" # "#3a4254"
secondaryBackgroundColor="#b3d4ff" # "#003478"#"#134b9e" 

textColor="black" #"#ffca00" #"#262730"
